language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
